#print('hellow')
#print("me neme is")
#print("gega")
#print("end me are")
#print("12 old")
#print("me second neme is")
#print("sadaghashvili")
#print("end me love coding")
#print("olsow plaing futbol")
#print("end me love math")
#print("olsow")
#print("me love")
#print("spiking georgian")
#print("russa")
#print("end inglish")
#print("me love world histore")
#print("like ww2")
#print("ww1")
#print("end mor")
#print('olsow me wont frends')
#print('end me got frends in goa')

print("hellow " + "me neme is " + "gega " + "end me are " + "12 old " + "me second neme is " + "sadaghashvili " + "end me love coding " + "olsow plaing futbol " + "end me love math " + "olsow " + "me love " + "spiking georgian " + "russa " + "end inglish  " + "me love world histore " + "like ww2 " + "ww1 " "end mor " +"olsow me wont frends " + "end me got frends in goa")