sentence = input("Введите предложение: ")
old_word = input("Какое слово заменить? ")
new_word = input("На какое слово заменить? ")
modified_sentence = sentence.replace(old_word, new_word)
print("Измененное предложение:", modified_sentence)
